name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, "**"]
    paths-ignore:
      - "CHANGELOG.md"
            
jobs:
  info:
    name: Rust Info
    runs-on: ubuntu-latest
    steps:
      - name: Rustup Show
        shell: bash
        run: rustup show
      - name: Rustup Version
        shell: bash
        run: rustup --version

  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: stable
      - run: cargo check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: nightly
          components: rust-src
      - uses: cargo-bins/cargo-binstall@75b4bfae1b2c753a6806bbce6e6cb89b602de33c # v1.22.0
      - run: cargo binstall cargo-expand --no-confirm
      - run: cargo test
      - run: cargo test --all-features

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: nightly
          components: clippy
      - run: cargo clippy --workspace --all-targets --all-features --tests --examples --benches -- -D warnings

  minimal_versions:
    name: Compile and test with minimal versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@d1b083a03f205b2b9135b1a2d9bad26e57da7df2 # cargo-hack
      - uses: taiki-e/install-action@1752480e043361484a9a04d5ccf3a8826dd900f7 # cargo-minimal-versions
      - name: minimal-versions check
        run: cargo minimal-versions check --workspace --tests --ignore-private -v

  msrv:
    name: Verify minimal supported rust version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: nightly
      - uses: taiki-e/install-action@d1b083a03f205b2b9135b1a2d9bad26e57da7df2 # cargo-hack
      - run: cargo hack check --rust-version --lib --ignore-private
